# Author: Saurav Samantray
# All rights reserved. Copyright (c) COHOTZ PEOPALYTICS LLP
version: "3.8"
services:
  db:
    image: postgres:14
    container_name: pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product-management-db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: saurav@gmail.com
      PGADMIN_DEFAULT_PASSWORD: saurav
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: